name: "Unit Tests"
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Create artifacts directory
      run: |
        mkdir artifacts
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Run tests
      run: |
        ./scripts/test.sh 2> >(tee artifacts/test_results.txt)
    - uses: actions/upload-artifact@v1
      with:
        name: Artifacts
        path: artifacts
